=== byron-hawkins/decaf-java/decaf/com/bitwise/decaf/editor/config/config.dtd
<?xml version='1.0' encoding='UTF-8' ?>

<!--
	<!DOCTYPE config PUBLIC "-//HawkinsSoftware//DTD config 1.0//EN" "http://somewhere/dtd/config.dtd">
-->

<!--
Document structure:

<EditorConfig>
	<Setup>
		<InstallRoot>
		<BrowserCommand>
		<PluginsPackage>
		<CompileCommand>
	<ClassComponents>
		<NameComponent>		(see below)
		<CustomComponent*>	
	<MethodComponents>
		<NameComponent>		(see below)
		<ReturnComponent>	
		<CustomComponent*>	
	<ParameterComponents?>
		<NameComponent>		(see below)
		<TypeComponent>		
		<CustomComponent*>	
	<FieldComponents?>
		<NameComponent>		(see below)
		<TypeComponent>		
		<CustomComponent*>	
	<LocalComponents?>
		<NameComponent>		(see below)
		<TypeComponent>		
		<CustomComponent*>	
	<Grammars?>
		<Phrase*>
		<Sentence*>
	<TypeChooserContent?>
		<TypeCategory>
			<TypeItem*>
	<TypeDefinitions?>
		<TypeDefinition*>
			<Discussion?>
			<Field*>
			<Method*>
				<Discussion?>
				<Parameter*>
				
	---- end of structure ----
	
	

Common elements:

	<NameComponent>
		<classname>
		<Label?>
		<FormLocation>
	<ReturnComponent>
		<classname>
		<Label?>
		<FormLocation>
	<TypeComponent>
		<classname>
		<Label?>
		<FormLocation>
	<CustomComponent>
		<classname>
		<FormLocation>
-->

<!-- ++++++++++++++ Root ++++++++++++++ -->

<!--
The EditorConfig element is the root element of this Decaf configuration
specification format.  
-->
<!ELEMENT EditorConfig (Setup, ClassComponents, MethodComponents, ParameterComponents?, FieldComponents?, LocalComponents?, Grammars?, TypeChooserContent?, TypeDefinitions?)>



<!-- ++++++++++++++ Setup +++++++++++++++ -->

<!--
The Setup element contains information required by Decaf at startup.
-->
<!ELEMENT Setup (InstallRoot,BrowserCommand,PluginsPackage,CompileCommand)>

<!--
The InstallRoot element specifies the absolute path of the root 
directory of the Decaf demo installation.  Unless it's been changed,
the directory itself will be named "decaf_demo" 
-->
<!ELEMENT InstallRoot (#PCDATA)>

<!--
Not currently used
-->
<!ELEMENT BrowserCommand (#PCDATA)>

<!-- 
The PluginsPackage element specifies the package name that is applied 
to all user plugins.  The user currently has no options regarding package 
name or even directory of compilation output, so as to simplify the 
situation.  Therefore output location is determined here.
-->
<!ELEMENT PluginsPackage (#PCDATA)>

<!--
The system command for the Java compiler.  Please use absolute path to
avoid path issues.  Default is $decaf_demo/bin/jikes
-->
<!ELEMENT CompileCommand (#PCDATA)>


<!-- ++++++++++++++ Editor Components +++++++++++++++ -->

<!--
The ClassComponents element is loaded by the ClassEditor on Decaf startup 
and used as a template for constructing its display.  The NameComponent is 
required, as all classes must minimally have a name.  Any further facilities 
are added with CustomComponent elements.
-->
<!ELEMENT ClassComponents (NameComponent,CustomComponent*)>

<!--
The MethodComponents element is loaded by the MethodEditor on Decaf startup
and used as a template for constructing its display.  The NameComponent and
ReturnComponent are required, since all methods must minimally have a name
and return type.  Further factilites can be provided through the CustomComponent
element.
-->
<!ELEMENT MethodComponents (NameComponent,ReturnComponent,CustomComponent*)>

<!--
The ParameterComponents, FieldComponents and LocalComponents elements are loaded 
by the VariableEditor on Decaf startup and used as a template for constructing its 
display of method parameters, class fields and local variables, respectively.
The NameComponent and TypeComponent are required as minimal constituents of a 
variable.  Further facilities are be provided with the CustomComponent element
-->
<!ELEMENT ParameterComponents (NameComponent,TypeComponent,CustomComponent*)>
<!ELEMENT FieldComponents (NameComponent,TypeComponent,CustomComponent*)>
<!ELEMENT LocalComponents (NameComponent,TypeComponent,CustomComponent*)>

<!--
The NameComponent, ReturnCompnent and TypeComponent each specify a subclass of 
java.awt.Component that displays and provides facilities for the user to edit 
the name, return type or variable type of its corresponding entity (respectively).
The NameComponent must implement com.bitwise.decaf.editor.DecafTextComponent,
and the ReturnComponent and TypeComponent must implement DecafTypeComponent.
The classname specifies the component class, which will be instantiated with 
its requisite default no-arg constructor.  The Represents element specifies the
field in the corresponding code construct that the component applies to; see the 
element for more information.  The Label and FormLocation specify parameters to
org.hs.jfc.FormLayout, which is used to assemble the main panel of the editor.
-->
<!ELEMENT NameComponent (classname, Label?, FormLocation)>
<!ELEMENT ReturnComponent (classname, Label?, FormLocation)>
<!ELEMENT TypeComponent (classname, Label?, FormLocation)>

<!--
The CustomComponent element specifies a java.awt.Component to be used in a
ClassEditor, MethodEditor or VariableEditor.  The component class, specified by
the classname sub-element, must implement com.bitwise.decaf.editor.MaskComponent
and org.hs.jfc.HotComponent.  The FormLocation specifies parameters to the editor's 
org.hs.jfc.FormLayout, which is used to lay out its main panel.
-->
<!ELEMENT CustomComponent (classname, FormLocation)>

<!--
The Represents element is not currently being used, since I've decided to code 
this information into the component classes themselves.  Were it used, it would
specify the public instance field of the subclass of org.hs.generator.GConstruct 
that is being edited by the declaring component.  It is resolved at Decaf startup 
to a java.lang.reflect.Field by first resolving the java.lang.Class for classname 
and then calling getField() with the fieldname.  
<!ELEMENT Represents (classname, fieldname)>
-->

<!--
The classname element represents the fully qualified classname of an editor entity
-->
<!ELEMENT classname (#PCDATA)>

<!--
The fieldname element represents the name by which the intended field can be found
through call to java.lang.Class.getField(String).
-->
<!ELEMENT fieldname (#PCDATA)>

<!--
The Label element specifies label text to go with a field of an editor.
-->
<!ELEMENT Label (#PCDATA)>

<!--
The FormLocation element specifies parameters to an instance of org.hs.jfc.FormLayout,
which presumably is being applied by the entity that declares this FormLayout element. 
-->
<!ELEMENT FormLocation (row, column, fillRightPct?)>

<!-- See element FormLocation -->
<!ELEMENT row (#PCDATA)>

<!-- See element FormLocation -->
<!ELEMENT column (#PCDATA)>

<!-- See element FormLocation -->
<!ELEMENT fillRightPct (#PCDATA)>

<!-- See element FormLocation -->
<!ATTLIST FormLocation mode (DEFAULT|FREE_LABEL|FREE_FIELD|LABEL_ON_TOP) "DEFAULT">



<!-- ++++++++++++++ Editor Grammars +++++++++++++++ -->

<!--
The Grammars element specifies a list of grammars available to Decaf.  A grammar
must implement com.bitwise.decaf.editor.grammar.GrammarMask, and will be included
in the Sentence and/or Phrase menu as indicated by this element.
-->
<!ELEMENT Grammars (Phrase*,Sentence*)>

<!-- 
The Phrase element specifies the classname of a grammar component, which must
implement com.bitwise.decaf.editor.grammar.GrammarMask.  It will be resolved at
Decaf startup and queried for a Collection of actions, via GrammarMask method
phraseGrammars(), that will be placed in the system's Phrase menu.
-->
<!ELEMENT Phrase (#PCDATA)>

<!-- 
The Sentence element specifies the classname of a grammar component, which must
implement com.bitwise.decaf.editor.grammar.GrammarMask.  It will be resolved at
Decaf startup and queried for a Collection of actions, via GrammarMask method
sentenceGrammars(), that will be placed in the system's Phrase menu.
-->
<!ELEMENT Sentence (#PCDATA)>



<!-- ++++++++++++++ Type Chooser +++++++++++++++ -->

<!--
The TypeChooserContent element specifies the contents of the type tree in the
com.bitwise.decaf.editor.TypeChooser.  Available types are contained in a single
layer of TypeCategory, and are specified by the uid attribute of the TypeDefinition
to which they correspond.  Documentation that shows up in the TypeChooser is 
specified by the TypeDefinition element. 
-->
<!ELEMENT TypeChooserContent (TypeCategory*)>

<!--
The TypeCategory specifies a category node in the TypeChooser's type tree.
-->
<!ELEMENT TypeCategory (TypeItem*)>

<!--
The name attribute of a TypeCategory element specifies the category name in text.
-->
<!ATTLIST TypeCategory name CDATA #REQUIRED>

<!--
The TypeItem element specifies a type in the TypeChooser's type tree by uid reference 
to a TypeDefinition element.
-->
<!ELEMENT TypeItem EMPTY>

<!--
The uid attribute of a TypeItem element refers to a TypeDefinition element.
-->
<!ATTLIST TypeItem uid IDREF #REQUIRED>


<!-- ++++++++++++++ Type Definitions +++++++++++++++ -->

<!ELEMENT TypeDefinitions (TypeDefinition*)>

<!--
A TypeDefinition element provides information about a type (a java.lang.Class,
that is) to the system.  It offers a discussion of the type, to be made visible
in the TypeChooser, if not elsewhere; and provides a listing of known fields and
methods.  These latter entities may be themselves described in detail, or they 
may be hidden from the user (to avoid the clutter of unusable class members).
-->
<!ELEMENT TypeDefinition (Discussion?,Field*,Method*)>

<!--
The Classname attribute specifies the fully qualified classname of the type to 
which this TypeDefinition refers.  The value "#user" is specially understood to
refer to the user's plugin class (whatever its name turns out to be).  This allows
the system to be configured with documentation for expected plugin methods.
-->
<!ATTLIST TypeDefinition Classname CDATA #REQUIRED>	

<!--
The uid attribute provides an identifier by which other elements in the xml document
implement this DTD may refer to this TypeDefinition.  The uid is also the name that 
appears for this type throughout Decaf, so choose with the user's understanding in mind.
-->
<!ATTLIST TypeDefinition uid ID #REQUIRED>

<!--
The superMethods attribute specifies which super class methods of the specified
type should be included in the system.  A value of ALL includes all methods available.
A value of DETAILED will exclude all super class methods not detailed in 
this TypeDefinition element (by a Method sub-element).
-->
<!ATTLIST TypeDefinition superMethods (ALL|DETAILED) "DETAILED">

<!--
The declaredMethods attribute specifies which declared methods of the specified
type should be included in the system.  A value of ALL includes all methods available.
A value of DETAILED will exclude all declared methods not detailed in 
this TypeDefinition element (by a Method sub-element). 
-->
<!ATTLIST TypeDefinition declaredMethods (ALL|DETAILED) "ALL">

<!--
The Method element specifies a method of a Java type (a java.lang.Class), and may provide
detailed information about it for display in the TypeChooser (and elsewhere), or may simply
hide the method from view (especially if it is not usable in the current context of Decaf).
-->
<!ELEMENT Method (Discussion?,Parameter*)>

<!--
The name attribute specifies the name of the Method.
-->
<!ATTLIST Method name CDATA #REQUIRED>

<!--
The hide attribute, if true, will prevent the Method from appearing in the TypeChooser.
-->
<!ATTLIST Method hide (true|false) "false">

<!--
The Field element specifies a field of a Java type (a java.lang.Class), and may hide the
field from view (especially if it is not usable in the current context of Decaf).  It may
contain a discussion, which should be entered as the body of the element.
-->
<!ELEMENT Field (#PCDATA)>		

<!--
The name attribute specifies the name of the Field.
-->
<!ATTLIST Field name CDATA #REQUIRED>

<!--
The hide attribute, if true, prevents this Field from showing up in the TypeChooser.
-->
<!ATTLIST Field hide (true|false) "false">

<!--
The Parameter element specifies a parameter to a method, in a Method element, so as to 
uniquely identify the method.  It may contain a discussion, which should be entered as 
the body of the element.
-->
<!ELEMENT Parameter (#PCDATA)>	

<!--
The type attribute refers to a TypeDefinition, by uid, that specifies the type 
(java.lang.Class) of the Parameter.  Implied here is that for every method made 
explicitly available to Decaf, each of its parameter's types must be explicitly 
declared in a TypeDefinition element.
-->
<!ATTLIST Parameter type IDREF #REQUIRED>

<!--
The name attribute refers to the name of the Parameter; it is arbitrary, and serves 
only to clarify the purpose of the parameter to the user.  The Parameter name will
show up in the TypeChooser, and in grammar components making use of the methods of 
external types (i.e., types not currently being created by the user).
-->
<!ATTLIST Parameter name CDATA "">

<!--
The dimensions attribute refers to the array dimensions of the Parameter.  A value of 
zero, which is the default, will of course indicate that the parameter is not of an 
array type.  
-->
<!ATTLIST Parameter dimensions CDATA "0">

<!--
The discussion element provides documentation for its declaring element, usually 
oriented towards the user and geared for their expected purpose and level of 
understanding.  Discussions will show up in the TypeChooser, and may be made use
of by custom components throughout the system.
-->
<!ELEMENT Discussion (#PCDATA)>

=== byron-hawkins/decaf-java/umail/config.xml
<?xml version='1.0' encoding='UTF-8' ?>

<!DOCTYPE config PUBLIC "-//HawkinsSoftware//DTD config 1.0//EN" "http://somewhere/dtd/config.dtd">

<EditorConfig>
	<Setup>
		<InstallRoot>c:\dev\decaf_demo</InstallRoot>
		<BrowserCommand></BrowserCommand>
		<PluginsPackage>com.bitwise.umail</PluginsPackage>
		<CompileCommand>c:\dev\decaf_demo\bin\jikes</CompileCommand>
	</Setup>
	<ClassComponents>
		<NameComponent>
			<classname>com.bitwise.decaf.editor.DTextField</classname>
			<FormLocation>
				<row>0</row>
				<column>0</column>
			</FormLocation>
		</NameComponent>
		<CustomComponent>
			<classname>com.bitwise.decaf.editor.Fields</classname>
			<FormLocation mode="LABEL_ON_TOP">
				<row>10</row>
				<column>0</column>
			</FormLocation>
		</CustomComponent>
		<CustomComponent>
			<classname>com.bitwise.decaf.editor.MethodsBox</classname>
			<FormLocation mode="LABEL_ON_TOP">
				<row>20</row>
				<column>0</column>
			</FormLocation>
		</CustomComponent>
	</ClassComponents>
	<MethodComponents>
		<NameComponent>
			<classname>com.bitwise.decaf.editor.DTextField</classname>
			<FormLocation>
				<row>0</row>
				<column>0</column>
			</FormLocation>
		</NameComponent>
		<ReturnComponent>
			<classname>com.bitwise.decaf.editor.DTypeBox</classname>
			<FormLocation>
				<row>10</row>
				<column>0</column>
			</FormLocation>
		</ReturnComponent>
		<CustomComponent>
			<classname>com.bitwise.decaf.editor.Parameters</classname>
			<FormLocation mode="LABEL_ON_TOP">
				<row>20</row>
				<column>0</column>
			</FormLocation>
		</CustomComponent>
	</MethodComponents>
	<ParameterComponents>
		<NameComponent>
			<classname>com.bitwise.decaf.editor.DTextField</classname>
			<FormLocation>
				<row>0</row>
				<column>0</column>
			</FormLocation>
		</NameComponent>
		<TypeComponent>
			<classname>com.bitwise.decaf.editor.DTypeBox</classname>
			<FormLocation>
				<row>10</row>
				<column>0</column>
			</FormLocation>
		</TypeComponent>
	</ParameterComponents>
	<FieldComponents>
		<NameComponent>
			<classname>com.bitwise.decaf.editor.DTextField</classname>
			<FormLocation>
				<row>0</row>
				<column>0</column>
			</FormLocation>
		</NameComponent>
		<TypeComponent>
			<classname>com.bitwise.decaf.editor.DTypeBox</classname>
			<FormLocation>
				<row>10</row>
				<column>0</column>
			</FormLocation>
		</TypeComponent>
	</FieldComponents>
	<LocalComponents>
		<NameComponent>
			<classname>com.bitwise.decaf.editor.DTextField</classname>
			<FormLocation>
				<row>0</row>
				<column>0</column>
			</FormLocation>
		</NameComponent>
		<TypeComponent>
			<classname>com.bitwise.decaf.editor.DTypeBox</classname>
			<FormLocation>
				<row>10</row>
				<column>0</column>
			</FormLocation>
		</TypeComponent>
	</LocalComponents>
	<Grammars>
		<Phrase>com.bitwise.decaf.editor.grammar.If</Phrase>
		<Phrase>com.bitwise.decaf.editor.grammar.Binary</Phrase>
		<Phrase>com.bitwise.decaf.editor.grammar.Comparison</Phrase>
		<Phrase>com.bitwise.decaf.editor.grammar.Access</Phrase>
		<Sentence>com.bitwise.decaf.editor.grammar.LocalVariable</Sentence>
		<Sentence>com.bitwise.decaf.editor.grammar.If</Sentence>
		<Sentence>com.bitwise.decaf.editor.grammar.While</Sentence>
		<Sentence>com.bitwise.decaf.editor.grammar.Binary</Sentence>
		<Sentence>com.bitwise.decaf.editor.grammar.Access</Sentence>
		<Sentence>com.bitwise.decaf.editor.grammar.Report</Sentence>
		<!--<Sentence>com.bitwise.decaf.editor.grammar.Return</Sentence>-->
	</Grammars>
	<TypeChooserContent>
		<TypeCategory name="uMail">
			<TypeItem uid="Account"/>
			<TypeItem uid="User"/>
			<TypeItem uid="DataDisplay"/>
			<TypeItem uid="Folder"/>
			<TypeItem uid="FolderMenuOption"/>
			<TypeItem uid="FolderMenuPlugin"/>
			<TypeItem uid="Menu"/>
			<TypeItem uid="Plugin"/>
			<TypeItem uid="Message"/>
			<TypeItem uid="MessageDisplay"/>
			<TypeItem uid="MessageInput"/>
			<TypeItem uid="MessageMenuOption"/>
			<TypeItem uid="Prompt"/>
		</TypeCategory>
		<TypeCategory name="Basic">		
			<TypeItem uid="Number"/>
			<TypeItem uid="True/False"/>
			<TypeItem uid="Void"/>
		</TypeCategory>
		<TypeCategory name="Foundation">		
			<TypeItem uid="Anything"/>
			<TypeItem uid="Text"/>
			<TypeItem uid="Date"/>
			<TypeItem uid="List"/>
			<TypeItem uid="ListWalk"/>
			<TypeItem uid="ListWalk2"/>
			<TypeItem uid="System"/>
			<TypeItem uid="NumberClass"/>
		</TypeCategory>
	</TypeChooserContent>
	<TypeDefinitions>

		<!-- Expected User Methods -->

		<TypeDefinition Classname="#user" uid="#none">
			<Method name="createMessage">
				<Discussion>
					This method collects information from the user for a new email message.  The server 
					has created the message for you and placed it in messageInput.getMessage().  The 
					messageInput object also contains standard prompts for the toAddress, subject, and 
					message body.  Feel free to customize these before using them to gather user input 
					for the message.  Note: if there is no recipient specified, the server will not 
					deliver the message.
				</Discussion>
				<Parameter type="Account" name="fromAccount">
					This is the sender's email account.
				</Parameter>
				<Parameter type="MessageInput" name="messageInput">
					This is the message input facility.  It contains prompts for each of the 
					message components: to, subject and body.  It also contains the message
					itself, initialized with your email address as the sender.
				</Parameter>
			</Method>
			<Method name="getFolderMenu">
				<Discussion>
					This method assembles the folder menu, listing the messages and sub-folders of the current
					folder, along with any context-related functions you would like to offer the user.  Typically
					the menu needs to contain a "Delete" item.  The server will append an item "Done" that steps
					up to the parent menu of this menu.
				</Discussion>
				<Parameter type="Account" name="currentAccount">
					The account being viewed.
				</Parameter>
				<Parameter type="Folder" name="currentFolder">
					The folder being viewed.
				</Parameter>
				<Parameter type="Menu" name="thisMenu">
					The menu we are constructing for display.
				</Parameter>
			</Method>
			<Method name="getPluginMenu">
				<Discussion>
					This method assembles the plugins menu, which offer the user plugin functions that run without
					any particular context (unlike the folder menu, which operates in the context of a particular
					mail folder).  The menu expects objects of type Plugin.
				</Discussion>
				<Parameter type="Account" name="currentAccount">
					The account being accessed.
				</Parameter>
				<Parameter type="Menu" name="pluginMenu">
					The plugin menu, awaiting your customized selections.
				</Parameter>
			</Method>
			<Method name="exit">
				<Discussion>
					This method is run when the user exits the uMail application.  You might give a "goodbye" message,
					delete items from a "Deleted Items" folder, etc.
				</Discussion>
				<Parameter type="Account" name="currentAccount">
					The account being exited.
				</Parameter>
			</Method>
			<Method name="displayMessage">
				<Discussion>
					This method displays a message to the screen, and is immediately followed by the folder menu.
					The messageDisplay object contains the message, and facilities for displaying it to screen.
				</Discussion>
				<Parameter type="Account" name="currentAccount">
					The account being viewed.
				</Parameter>
				<Parameter type="MessageDisplay" name="messageDisplay">
					This object contains the message in getMessage(), and a DataDisplay facility for each field of
					the message.  Be sure to call init() before displaying any of the message values.  The method 
					align() will properly align the values column.
				</Parameter>
			</Method>
			<Method name="sendMail">
				<Discussion>
					This method is run after the user has created a message, but before it is actually
					sent.  You might want to put a copy in a "Sent Items" folder, or send a copy to the 
					user's alternate account.  The server of course performs the actual task of sending
					the message to its destination.
				</Discussion>
				<Parameter type="Account" name="currentAccount">
					The sender's account.
				</Parameter>
				<Parameter type="Message" name="message">
					The message being sent; it has already been created and contains the appropriate information, 
					though you are free to make changes such as automated keyword replacements.
				</Parameter>
			</Method>
			<Method name="receiveMail">
				<Discussion>
					This method runs when a message is received by an account.  It is responsible for putting 
					the message in the user's inbox, or filing it in some other appropriate folder.  You might
					want to delete messages under certain criteria, or perhaps notify the user in the case of
					a particularly important arrival.
				</Discussion>
				<Parameter type="Account" name="currentAccount">
					The recipient's account.
				</Parameter>
				<Parameter type="Message" name="message">
					The message being received.
				</Parameter>
			</Method>
			
		</TypeDefinition>

		<!-- jType`s -->

		<TypeDefinition Classname="com.bitwise.umail.SWIGTYPE_p_void" uid="SwigVoid"/>
		<TypeDefinition Classname="com.bitwise.umail.jType" uid="MenuOption"/>	
			<!-- for now, MenuOption is the only user application of the generic jType -->

		<TypeDefinition Classname="com.bitwise.umail.jAccount" uid="Account">
			<Discussion>
				An email account.
			</Discussion>
			<Method name="getRoot">
				<Discussion>
					Returns the top folder of the tree of email folders.
				</Discussion>
			</Method>
			<Method name="log">	
				<Discussion>
